server:
  port: 8071
spring:
  application:
    name: metadata-files-service
zookeeper:
  url: ${ZOOKEEPER_URL:127.0.0.1:2181}
  sleep-ms-between-retries: 100
  max-retries: 3
  base-path: /files
logging:
  level:
    com.modsen.metadatafilesservice: debug