spring:
  codec:
    max-in-memory-size: 500KB
  application:
    name: downloader-files-service
metadata-service:
  url: ${METADATA_SERVICE_URL:http://localhost:8071}
kafka:
  message-size: 512000
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    group-id: file-consumer-group
    auto-offset-reset: earliest
    enable-auto-commit: false
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

logging:
  level:
    com.modsen.downloaderfilesservice: debug
server:
  port: 8082
